# Generated by Django 5.2.1 on 2025-05-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="show_minimap",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="word_wrap",
            field=models.BooleanField(default=True),
        ),
    ]
